tconfig:
  concurrency_jobs: 2
  concurrency_commands: 6
  test_times: 1
  debug: false
  duration: 0

  tool:
    bash: bash
    capinfos: capinfos
    editcap: editcap
    tcpdump: tcpdump
    tcprewrite: tcprewrite
    tcpprep: tcpprep

  modifier:
    adjust_time: true  # default is false, you must set it explicit
    time_offset: 0s
    keep_ip: false
    c1: 192
    c2: 168
    c3: 186
    c4: 11
    s1: 10
    s2: 132
    s3: 123
    s4: 22
    use_part_3: false
    use_part_4: false

  finder:
    directory: /data/.prsdata/pcaps/

modifiers:
  - id: keep-ip
    adjust_time: true
    keep_ip: true

finders:
  - id: ftp-keep-ip
    directory: /data/.prsdata/pcaps/
    patterns:
      - ftp
      - fet/ftp
    modifier: keep-ip

  - id: auth
    directory: /data/.prsdata/pcaps/
    patterns:
      - ftp
      - http
      - redis
      - socks
      - http
      - smtp
      - pop3
      - imap
      - mysql
      - ntlm
      - kerberos
      - ssh
      - radius
      - fet/imap

  - id: file
    directory: /data/.prsdata/pcaps/fet/

jobs:

  - id: matrix
    name: matrix
    enable: true
    commands:
      - name: matrix
        vars:
          prefix: abcd
        command: cd {{.FinderDirectory}} && /usr/bin/python2 /root/git/matrix/py/matrix-pcap.py --prefix {{.prefix}} -f {{.RelativePath}} -d 0.5
        
  - id: pcap-replay
    name: pcap-replay
    enable: false
    commands:
      - name: pcap-replay
        command: cd {{.FinderDirectory}} && /usr/bin/python2 /root/git/matrix/py/matrix-pcap.py --pcap-id {{.pcap_id}} -f {{.RelativePath}} -d 0.5
        
  - id: matrix-ftp
    name: matrix-ftp
    enable: false
    finder: ftp-keep-ip
    commands:
      - name: matrix-ftp
        vars:
          prefix: abcd
        command: cd {{.FinderDirectory}} && /usr/bin/python2 /root/git/matrix/py/matrix-pcap.py  --prefix {{.prefix}} -f {{.RelativePath}} -d 0.5

  - id: auth
    name: auth
    enable: false
    finder: auth
    commands:
      - name: auth
        vars:
          prefix: abcd
        command: cd {{.FinderDirectory}} && /usr/bin/python2 /root/git/matrix/py/matrix-pcap.py  --prefix {{.prefix}} -f {{.RelativePath}} -d 0.5

  - id: file
    name: file
    enable: false
    finder: file
    commands:
      - name: file
        vars:
          prefix: abcd
        command: cd {{.FinderDirectory}} && /usr/bin/python2 /root/git/matrix/py/matrix-pcap.py  --prefix {{.prefix}} -f {{.RelativePath}} -d 0.5
